### ISSUE TITLE
Create Mock Team page in mobirise page with info from this repository

### ISSUE THREAD

**Issue by VonSub** [threefoldfoundation/data_team#10]
Let's see if we can use the team macro's for Mobirise as well.
Make a simple website with different sections with different filters applied.

**Comment by ehab-hassan** [comment]
repo created at 
https://github.com/threefoldfoundation/ifram_datateams/tree/development
link of the wiki page
https://wiki.team.grid.tf/wiki/wiki_team#/threefold_tech

**Comment by ehab-hassan** [comment]
it works good without description show. because 
ifram show scrollbar when clicking at the image
if we give it some space at the bottom for description ll be huge space between sections
![team](https://user-images.githubusercontent.com/10484295/61642143-b1d85380-aca0-11e9-98ab-21424d8f869f.jpg)
ll try to find a way how to fix that if anyone had suggestions ll help :)

**Comment by ehab-hassan** [comment]
@abom can we change at CSS so we can make the content-box show at all image, not at the bottom like this
![photo_2019-07-23_08-16-53](https://user-images.githubusercontent.com/10484295/61691465-e9401200-ad2b-11e9-9600-acb98ccfacd4.jpg)

also the color

**Comment by abom** [comment]
@ehab-hassan You can change [team.js](https://github.com/threefoldtech/jumpscale_weblibs/tree/master/static/team) css (this will be applied for all places where team macro is used).

Or we can add this options to the macro itself (box position, colors...etc), but this will need more time for testing.

**Comment by VonSub** [comment]
@ehab-hassan status?

**Comment by ehab-hassan** [comment]
still try to figure how to make ifram take the full size of all image with content and make it responsive at mobile and tablet because this solution 
![61691465-e9401200-ad2b-11e9-9600-acb98ccfacd4](https://user-images.githubusercontent.com/10484295/62031196-18042f80-b1e7-11e9-8e6f-64c556924c86.jpg)

not work

**Comment by ehab-hassan** [comment]
test1
https://www2.datateam.grid.tf/about-us.html

**Comment by VonSub** [comment]
mobile Iframe does not scale to the content so it becomes scrollable, not really desired UX

**Comment by ehab-hassan** [comment]
the mobile iframe is fixed now

**Comment by ehab-hassan** [comment]
mobile Iframe scroll fixed
